version: '3'
services:
  discord_bot:
    restart: always
    build: .
    working_dir: /root/src
    tty: true
    volumes:
      - ./src:/root/src
    env_file:
      - .env
    command: python bot.py

